version: '3'
services:
  mysql:
    image: circleci/mysql:5.7
    volumes:
      - data:/var/lib/mysql/
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: m_root_password
      MYSQL_DATABASE: m_database
      MYSQL_USER: m_user
      MYSQL_PASSWORD: m_password
volumes:
  data:
    driver: local
